# Generated by Django 4.2.4 on 2023-08-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_status_survey_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='date',
            new_name='deadline_date',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='time',
            new_name='deadline_time',
        ),
    ]
