# Generated by Django 3.2.8 on 2023-09-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_birthday'),
        ('events', '0002_alter_events_organizers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presents',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='presents',
            name='id_profile',
        ),
        migrations.AlterField(
            model_name='events',
            name='present',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
        migrations.DeleteModel(
            name='Interested',
        ),
        migrations.DeleteModel(
            name='Presents',
        ),
    ]
