# Generated by Django 3.2.8 on 2023-09-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_birthday'),
        ('events', '0003_auto_20230904_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='present',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile'),
        ),
        migrations.CreateModel(
            name='Presents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField(default=False)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile')),
            ],
        ),
    ]
