# Generated by Django 3.2.8 on 2023-09-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230912_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='present',
        ),
        migrations.RemoveField(
            model_name='interested',
            name='interested',
        ),
    ]
