# Generated by Django 4.2.4 on 2023-09-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventtypeoptions_remove_events_contribution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_type',
            new_name='e_type',
        ),
    ]
