# Generated by Django 4.2.4 on 2023-09-12 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_tickettype_max_number_to_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='remaining_tickets',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
