# Generated by Django 4.2.4 on 2023-09-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scan_done',
            field=models.BooleanField(default=False),
        ),
    ]
